# Generated by Django 4.1.6 on 2023-02-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gluecksrad', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playername',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='playername',
            name='description',
        ),
        migrations.RemoveField(
            model_name='playername',
            name='updated',
        ),
        migrations.AlterField(
            model_name='playername',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
