# Generated by Django 4.1.6 on 2023-02-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gluecksrad', '0002_rename_created_playername_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerName',
            new_name='Player',
        ),
    ]
