# Generated by Django 4.1.5 on 2023-02-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gluecksrad', '0004_remove_player_created_at_alter_player_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('word', models.CharField(max_length=100)),
            ],
        ),
    ]
