# Generated by Django 4.1.5 on 2023-02-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gluecksrad', '0007_rename_word_text_word_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
